version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: tamerx-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tamerx_root_password_change_me
      MYSQL_DATABASE: tamerx_inventory
      MYSQL_USER: tamerx_user
      MYSQL_PASSWORD: tamerx_secure_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Optional: phpMyAdmin for easy database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: tamerx-phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: tamerx_user
      PMA_PASSWORD: tamerx_secure_password
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
    driver: local

networks:
  default:
    name: tamerx_network
