[build]
  command = "pnpm install && vite build"
  publish = "dist/public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# Redirect API requests to serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server"
  status = 200

# SPA fallback - serve index.html for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
